In [1]:
import pandas as pd 
df = pd.read_csv('diabetic_dataset.csv')
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_medications,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,1,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,18,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,13,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,16,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,8,NO
...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,51,16,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),1,4,5,5,33,18,NO
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,53,9,NO
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,45,21,NO
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,13,3,NO

In [2]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'num_lab_procedures', 'num_medications',
       'readmitted'],
      dtype='object')

In [3]:
df = df.rename(columns={'patient_nbr':'patient_id','time_in_hospital':'days_admitted','num_lab_procedures':'lab_tests_count','num_medications':'medicine_count'})
df

,encounter_id,patient_id,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,days_admitted,lab_tests_count,medicine_count,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,1,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,18,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,13,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,16,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,8,NO
...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,51,16,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),1,4,5,5,33,18,NO
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,53,9,NO
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,45,21,NO
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,13,3,NO

In [4]:
df.columns

Index(['encounter_id', 'patient_id', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'days_admitted', 'lab_tests_count', 'medicine_count', 'readmitted'],
      dtype='object')

In [5]:
df = df[['patient_id','encounter_id','gender','age','race','days_admitted',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
         'lab_tests_count', 'medicine_count', 'readmitted']]
df.columns

Index(['patient_id', 'encounter_id', 'gender', 'age', 'race', 'days_admitted',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'lab_tests_count', 'medicine_count', 'readmitted'],
      dtype='object')

In [9]:
(df['patient_id']==df['encounter_id']).all()

np.False_

In [10]:
df.head(10)

,patient_id,encounter_id,gender,age,race,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count,readmitted
0,8222157,2278392,Female,[0-10),Caucasian,1,6,25,1,41,1,NO
1,55629189,149190,Female,[10-20),Caucasian,3,1,1,7,59,18,>30
2,86047875,64410,Female,[20-30),AfricanAmerican,2,1,1,7,11,13,NO
3,82442376,500364,Male,[30-40),Caucasian,2,1,1,7,44,16,NO
4,42519267,16680,Male,[40-50),Caucasian,1,1,1,7,51,8,NO
5,82637451,35754,Male,[50-60),Caucasian,3,2,1,2,31,16,>30
6,84259809,55842,Male,[60-70),Caucasian,4,3,1,2,70,21,NO
7,114882984,63768,Male,[70-80),Caucasian,5,1,1,7,73,12,>30
8,48330783,12522,Female,[80-90),Caucasian,13,2,1,4,68,28,NO
9,63555939,15738,Female,[90-100),Caucasian,12,3,3,4,33,18,NO

In [12]:
df.shape

(101766, 12)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   patient_id                101766 non-null  int64
 1   encounter_id              101766 non-null  int64
 2   gender                    101766 non-null  object
 3   age                       101766 non-null  object
 4   race                      101766 non-null  object
 5   days_admitted             101766 non-null  int64
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   lab_tests_count           101766 non-null  int64
 10  medicine_count            101766 non-null  int64
 11  readmitted                101766 non-null  object
dtypes: int64(8), object(4)
memory usage: 9.3+ MB

In [18]:
df.describe()

,patient_id,encounter_id,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,5.433040e+07,1.652016e+08,4.395987,2.024006,3.715642,5.754437,43.095641,16.021844
std,3.869636e+07,1.026403e+08,2.985108,1.445403,5.280166,4.064081,19.674362,8.127566
min,1.350000e+02,1.252200e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.341322e+07,8.496119e+07,2.000000,1.000000,1.000000,1.000000,31.000000,10.000000
50%,4.550514e+07,1.523890e+08,4.000000,1.000000,1.000000,7.000000,44.000000,15.000000
75%,8.754595e+07,2.302709e+08,6.000000,3.000000,4.000000,7.000000,57.000000,20.000000
max,1.895026e+08,4.438672e+08,14.000000,8.000000,28.000000,25.000000,132.000000,81.000000

In [19]:
df.isnull().sum()

patient_id                  0
encounter_id                0
gender                      0
age                         0
race                        0
days_admitted               0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
lab_tests_count             0
medicine_count              0
readmitted                  0
dtype: int64

In [20]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
101761    False
101762    False
101763    False
101764    False
101765    False
Length: 101766, dtype: bool

In [21]:
df.duplicated().sum()

np.int64(0)

In [31]:
df['gender'].value_counts()

gender
Female     54708
Male       47055
Unknown        3
Name: count, dtype: int64

In [33]:
df['gender'] = df['gender'].replace('Unknown', 'Male')

In [34]:
df['gender'].value_counts()

gender
Female    54708
Male      47058
Name: count, dtype: int64

In [36]:
df['age'].value_counts(ascending=True)

age
[0-10)        161
[10-20)       691
[20-30)      1657
[90-100)     2793
[30-40)      3775
[40-50)      9685
[80-90)     17197
[50-60)     17256
[60-70)     22483
[70-80)     26068
Name: count, dtype: int64

In [39]:
df['race'].value_counts()

race
Caucasian          76099
AfricanAmerican    19210
Other               3779
Hispanic            2037
Asian                641
Name: count, dtype: int64

In [38]:
df['race'] = df['race'].replace('?','Other')

In [66]:
df['readmitted'].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [42]:
df['patient_id'].nunique()

71518

In [43]:
df['encounter_id'].nunique()

101766

In [45]:
df['days_admitted'].max()

14

In [46]:
df.dtypes

patient_id                   int64
encounter_id                 int64
gender                      object
age                         object
race                        object
days_admitted                int64
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
lab_tests_count              int64
medicine_count               int64
readmitted                  object
dtype: object

In [48]:
age_map = {
    '[0-10)': 5,
    '[10-20)': 15,
    '[20-30)': 25,
    '[30-40)': 35,
    '[40-50)': 45,
    '[50-60)': 55,
    '[60-70)': 65,
    '[70-80)': 75,
    '[80-90)': 85,
    '[90-100)': 95
}

df['ages'] = df['age'].map(age_map)
df['ages'].value_counts()

ages
75    26068
65    22483
55    17256
85    17197
45     9685
35     3775
95     2793
25     1657
15      691
5       161
Name: count, dtype: int64

In [50]:
df.drop('age',axis=1,inplace=True)
df

,patient_id,encounter_id,gender,race,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count,readmitted,ages
0,8222157,2278392,Female,Caucasian,1,6,25,1,41,1,NO,5
1,55629189,149190,Female,Caucasian,3,1,1,7,59,18,>30,15
2,86047875,64410,Female,AfricanAmerican,2,1,1,7,11,13,NO,25
3,82442376,500364,Male,Caucasian,2,1,1,7,44,16,NO,35
4,42519267,16680,Male,Caucasian,1,1,1,7,51,8,NO,45
...,...,...,...,...,...,...,...,...,...,...,...,...
101761,100162476,443847548,Male,AfricanAmerican,3,1,3,7,51,16,>30,75
101762,74694222,443847782,Female,AfricanAmerican,5,1,4,5,33,18,NO,85
101763,41088789,443854148,Male,Caucasian,1,1,1,7,53,9,NO,75
101764,31693671,443857166,Female,Caucasian,10,2,3,7,45,21,NO,85
101765,175429310,443867222,Male,Caucasian,6,1,1,7,13,3,NO,75

In [53]:
df = df[['patient_id', 'encounter_id', 'gender', 'race','ages','days_admitted',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'lab_tests_count', 'medicine_count', 'readmitted']]
df

,patient_id,encounter_id,gender,race,ages,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count,readmitted
0,8222157,2278392,Female,Caucasian,5,1,6,25,1,41,1,NO
1,55629189,149190,Female,Caucasian,15,3,1,1,7,59,18,>30
2,86047875,64410,Female,AfricanAmerican,25,2,1,1,7,11,13,NO
3,82442376,500364,Male,Caucasian,35,2,1,1,7,44,16,NO
4,42519267,16680,Male,Caucasian,45,1,1,1,7,51,8,NO
...,...,...,...,...,...,...,...,...,...,...,...,...
101761,100162476,443847548,Male,AfricanAmerican,75,3,1,3,7,51,16,>30
101762,74694222,443847782,Female,AfricanAmerican,85,5,1,4,5,33,18,NO
101763,41088789,443854148,Male,Caucasian,75,1,1,1,7,53,9,NO
101764,31693671,443857166,Female,Caucasian,85,10,2,3,7,45,21,NO
101765,175429310,443867222,Male,Caucasian,75,6,1,1,7,13,3,NO

In [60]:
df[['gender','race']]=df[['gender','race']].astype(str)

In [65]:
df.dtypes

patient_id                   int64
encounter_id                 int64
gender                      object
race                        object
ages                         int64
days_admitted                int64
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
lab_tests_count              int64
medicine_count               int64
readmitted                  object
dtype: object

In [67]:
df['treatment_intensity'] = df['lab_tests_count'] + df['medicine_count']

In [70]:
df['risk_score'] = (
    df['days_admitted'] * 0.4 +
    df['lab_tests_count'] * 0.3 +
    df['medicine_count'] * 0.3
)

In [73]:
def age_category(age):
    if age <= 18:
        return 'Child'
    elif age <= 35:
        return 'Young Adult'
    elif age <= 55:
        return 'Adult'
    elif age <= 75:
        return 'Middle Aged'
    else:
        return 'Senior'

df['age_category'] = df['ages'].apply(age_category)

In [74]:
df

,patient_id,encounter_id,gender,race,ages,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count,readmitted,treatment_intensity,risk_score,age_category
0,8222157,2278392,Female,Caucasian,5,1,6,25,1,41,1,NO,42,13.0,Child
1,55629189,149190,Female,Caucasian,15,3,1,1,7,59,18,>30,77,24.3,Child
2,86047875,64410,Female,AfricanAmerican,25,2,1,1,7,11,13,NO,24,8.0,Young Adult
3,82442376,500364,Male,Caucasian,35,2,1,1,7,44,16,NO,60,18.8,Young Adult
4,42519267,16680,Male,Caucasian,45,1,1,1,7,51,8,NO,59,18.1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,100162476,443847548,Male,AfricanAmerican,75,3,1,3,7,51,16,>30,67,21.3,Middle Aged
101762,74694222,443847782,Female,AfricanAmerican,85,5,1,4,5,33,18,NO,51,17.3,Senior
101763,41088789,443854148,Male,Caucasian,75,1,1,1,7,53,9,NO,62,19.0,Middle Aged
101764,31693671,443857166,Female,Caucasian,85,10,2,3,7,45,21,NO,66,23.8,Senior
101765,175429310,443867222,Male,Caucasian,75,6,1,1,7,13,3,NO,16,7.2,Middle Aged

In [78]:
df

,patient_id,encounter_id,gender,race,ages,age_category,days_admitted,admission_type_id,discharge_disposition_id,admission_source_id,lab_tests_count,medicine_count,readmitted,treatment_intensity,risk_score
0,8222157,2278392,Female,Caucasian,5,Child,1,6,25,1,41,1,NO,42,13.0
1,55629189,149190,Female,Caucasian,15,Child,3,1,1,7,59,18,>30,77,24.3
2,86047875,64410,Female,AfricanAmerican,25,Young Adult,2,1,1,7,11,13,NO,24,8.0
3,82442376,500364,Male,Caucasian,35,Young Adult,2,1,1,7,44,16,NO,60,18.8
4,42519267,16680,Male,Caucasian,45,Adult,1,1,1,7,51,8,NO,59,18.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,100162476,443847548,Male,AfricanAmerican,75,Middle Aged,3,1,3,7,51,16,>30,67,21.3
101762,74694222,443847782,Female,AfricanAmerican,85,Senior,5,1,4,5,33,18,NO,51,17.3
101763,41088789,443854148,Male,Caucasian,75,Middle Aged,1,1,1,7,53,9,NO,62,19.0
101764,31693671,443857166,Female,Caucasian,85,Senior,10,2,3,7,45,21,NO,66,23.8
101765,175429310,443867222,Male,Caucasian,75,Middle Aged,6,1,1,7,13,3,NO,16,7.2

In [80]:
!pip install pymysql sqlalchemy mysql
from sqlalchemy import create_engine

Requirement already satisfied: pymysql in c:\users\harsh\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\harsh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: mysql in c:\users\harsh\anaconda3\lib\site-packages (0.0.3)
Requirement already satisfied: greenlet>=1 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: mysqlclient in c:\users\harsh\anaconda3\lib\site-packages (from mysql) (2.2.8)

In [82]:
engine = create_engine('mysql+pymysql://root:Harshit%40404@localhost:3306/diabetic_patients')
df.to_sql('patients',engine,if_exists='replace',index=False)

101766